---
version: 1

update_configs:
  - package_manager: "python"
    directory: "/"
    update_schedule: "weekly"
    default_labels:
      - "dependencies"
      - "dependabot"
    commit_message:
      prefix: "chore"
    allowed_updates:
    - match:
        update_type: "all"
    target_branch: "master"
    automerged_updates:
    - match:
        dependency_type: "all"
