---
version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: monthly
  open-pull-requests-limit: 99
  target-branch: master
  labels:
  - dependencies
  - dependabot
  commit-message:
    prefix: chore
